# Generated by Django 4.2.11 on 2024-03-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
